
/************************************************************************/
/* TYPES.H                                                              */
/************************************************************************/

#define NULL 	0

#define OK     0
#define ERROR	1

#define FALSE	0
#define TRUE	1

typedef unsigned long   microword;         /* 32 bit micromir      */
typedef unsigned char   microaddress;      /* 8 bit address cstore */
typedef short              word;           /* 16 bit memoria       */
typedef unsigned short  address;           /* ~12 bit indirizzi    */

